-- This is entry point of the addon, do not edit this file unless you know what you're doing.
--
-- Name: Terminal
-- Author: Kot @ <github.com/Kotyarishka> @ <steamcommunity.com/id/Kotyarishka>
-- Description: 
-- @todo: Add description
-- License: MIT

mvp = {}

AddCSLuaFile()

if (SERVER) then
    AddCSLuaFile("mvp/cl_init.lua")
    AddCSLuaFile("mvp/sh_init.lua")

    include("mvp/sv_init.lua")
else
    include("mvp/cl_init.lua")
end

include("mvp/sh_init.lua")